- name: Install nginx
  become: true
  become_user: root
  apt: name={{ item }} state=present
  with_items:
    - nginx

- name: start nginx
  become: true
  become_user: root
  systemd:
    name: nginx
    state: started