- name: Update packages
  become: true
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Setup Environment
  become: true
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - python
    - python-mysqldb
    - npm

- name: change password for root user
  become: true
  user:
    name: root
    update_password: always
    password: "{{hashed_login_password}}"
