- name: Create mysql wordpress database
  mysql_db: name={{ wp_mysql_db }}
    state=present
    login_user={{login_user}}
    login_password={{login_password}}
  become: yes

- name: Create mysql wordpress user
  mysql_user: name={{ wp_mysql_user }}
    login_user={{login_user}}
    login_password={{login_password}}
    password={{ wp_mysql_password }}
    priv={{ wp_mysql_db }}.*:ALL
  become: yes

- name: Download WordPress
  get_url: url=https://wordpress.org/latest.tar.gz
    dest=/tmp/wordpress.tar.gz
    validate_certs=no

- name: Extract WordPress
  unarchive: src=/tmp/wordpress.tar.gz
    dest=/tmp/
    copy=no
  become: yes

- name: Ensures Directory and all containing files are deleted before re-installing. (Maintain Idempotence)
  file: path={{ wp_directory }} state=absent
  become: yes

- name: Creates directory
  file: path={{ wp_directory }}
    state=directory
  become: yes

# use shell module instead of command module to allow globbing
# https://stackoverflow.com/questions/43876766/how-can-i-move-all-files-in-a-directory-to-another-using-ansible-module
- name: Move wordpress
  shell: mv /tmp/wordpress/* {{ wp_directory }}
  become: yes

- name: Copy wp-config to wordpress
  template:
    src: wp-config.php
    dest: "{{ wp_directory }}"
    owner: root
    group: root
  become: yes

- name: Copy nginx config to sites-available
  template:
    src: wordpress.conf
    dest: /etc/nginx/sites-available/{{ wp_conf_name_nginx }}
    owner: root
    group: root
  become: yes

- name: Create symbolic link in sites-enabled.
  file:
    src: /etc/nginx/sites-available/{{ wp_conf_name_nginx }}
    dest: /etc/nginx/sites-enabled/{{ wp_conf_name_nginx }}
    state: link
  become: yes

- name: restart nginx
  service:
    name: nginx
    state: restarted
  become: yes
