- name: Create mysql wordpress database
  mysql_db: name={{ wp_mysql_db }} state=present
  become: yes

- name: Create mysql wordpress user
  mysql_user: name={{ wp_mysql_user }}
    password={{ wp_mysql_password }}
    priv=*.*:ALL
  become: yes

- name: Download WordPress
  get_url: url=https://wordpress.org/latest.tar.gz
    dest=/tmp/wordpress.tar.gz
    validate_certs=no

- name: Creates directory
  file: path=/var/www/mutant.city state=directory
  become: yes

- name: Extract WordPress
  unarchive: src=/tmp/wordpress.tar.gz dest=/var/www/mutant.city copy=no
  become: yes
