- name: Set MySQL root password before installing
  debconf: name='mysql-server' question='mysql-server/root_password' value='{{ mysql_root_pass | quote }}' vtype='password'
  become: true

- name: Confirm MySQL root password before installing
  debconf: name='mysql-server' question='mysql-server/root_password_again' value='{{ mysql_root_pass | quote }}' vtype='password'
  become: true

- name: Install Mysql package
  become: true
  apt: name={{ item }} state=present
  with_items:
    - mysql-server
    - mysql-client

- name: start mysql
  become: true
  become_user: root
  systemd:
    name: mysql
    state: started