- name: Remove old http conf. (Disable the http conf in favor of the https conf)
  file:
    path: /etc/nginx/sites-available/{{ http_conf_name_nginx }}
    state: absent
  become: true

- name: Remove symbolic link in sites-enabled for http conf. (Disable the http conf in favor of the https conf)
  file:
    path: /etc/nginx/sites-enabled/{{ http_conf_name_nginx }}
    state: absent
  become: true

- name: Copy nginx http config to sites-available
  template:
    src: wordpress-http.conf
    dest: /etc/nginx/sites-available/{{ http_conf_name_nginx }}
    owner: root
    group: root
  become: true

- name: Add symbolic link in sites-enabled for http conf.
  file:
    src: /etc/nginx/sites-available/{{ http_conf_name_nginx }}
    dest: /etc/nginx/sites-enabled/{{ http_conf_name_nginx }}
    state: link
  become: true

- name: restart nginx(to allow certbot to connect)
  service:
    name: nginx
    state: restarted
  become: true

- name: Create certificate (may take a minute or two) Note-> Theres a limite of certificates you're allowed per week!
  shell: ./certbot-auto certonly --webroot -w /var/www/{{ hostname }} -d {{ hostname }} --non-interactive --agree-tos --email {{ service_admin_email }}
  args:
    chdir: /opt/certbot

- name: Copy nginx https config to sites-available
  template:
    src: wordpress-https.conf
    dest: /etc/nginx/sites-available/{{ https_conf_name_nginx }}
    owner: root
    group: root
  become: true

- name: Add symbolic link in sites-enabled for https conf.
  file:
    src: /etc/nginx/sites-available/{{ https_conf_name_nginx }}
    dest: /etc/nginx/sites-enabled/{{ https_conf_name_nginx }}
    state: link
  become: true

- name: restart nginx
  service:
    name: nginx
    state: restarted
  become: true
