- name: Clone latest "Lets Encrypt" client master branch into /opt
  git:
    dest: /opt/certbot
    clone: yes
    repo: https://github.com/certbot/certbot
    force: yes
  become: true

# note: cron job as well
