- name: Add php apt package repo
  become: true
  apt_repository:
    repo: "ppa:ondrej/php"
    state: present
    validate_certs: no

- name: Install php7.2 and deps
  become: true
  become_user: root
  apt: name={{ item }} state=present
  with_items:
    - php7.2
    - php7.2-fpm
    - php7.2-enchant
    - php7.2-mbstring
    - php7.2-mysql
    - php7.2-xml
    - php7.2-curl
    - php7.2-gd
    - php7.2-mbstring
    - php7.2-xml
    - php7.2-xmlrpc

  notify: restart php7.2-fpm
