- name: Creates dump directory
  become: true
  file:
    path: /sql_dumps
    state: directory
    owner: root
    group: root
    mode: 700

- name: cron job to back up wordpress database weekly
  become: true
  cron:
    name: "Backup Wordpress Database"
    special_time: weekly
    job: "sudo mysqldump -u {{ wp_mysql_user }} -p {{ wp_mysql_password  }} database_name {{ wp_mysql_db }} > /sql_dumps/backup.sql"

# note: name is required here to prevent duplicates
- name: Add crontab to renew certificates
  cron:
    minute: "30"
    hour: "2"
    weekday: "1"
    job: /opt/certbot/certbot-auto renew >> /var/log/letsencrypt-renew.log
    name: a job to recheck certificates
  become: true
